### PR TITLE
added te/kill-current-tag, te/goto-tag-match, te/goto-tag-begging, te…

### PR DESCRIPTION
**Pull request by futurist**
…/goto-tag-end

Was these func make sense for daily use?

added te/kill-current-tag, te/goto-tag-match, te/goto-tag-begging, te/goto-tag-end func to make it more convenient.

### CODE REVIEW

**Comment by magnars** [comment]
Seems reasonable. Please add tests for the new features.

**Comment by futurist** [comment]
Added the new feature tests, and updated `evm` install script for correct travis env setup.

**Comment by magnars** [comment]
Excellent, thank you. One last tiny niggle: Please use the lispy style end parenthesis, with all on one line.

**Comment by futurist** [comment]
Changed, and added test for numeric arg kill-tag

**Comment by magnars** [comment]
Thanks!

**Pull request merged**
